# Generated by Django 2.0.5 on 2018-05-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default='', verbose_name='內容'),
            preserve_default=False,
        ),
    ]
